### ISSUE TITLE
Checklist for maturity

### ISSUE THREAD

**Issue by elliottower** [Farama-Foundation/stable-retro#21]
# Checklist for Maturity

- [x] Fully deterministic 
  - As far as possible
- [x] Explicit Versioning 
- [x] Farama Notifications
- [x] PyPI
- [x] Full Package Description 
- [x] Deploy via GH Actions 
- [x] Website
- [x] Linux and MacOS 
- [x] Precommit 
- [x] Typehinting 
- [x] Docstrings 
- [x] CI Testing 
- [x] Logo 
- [x] CoC 
- [x] Gymnasium/PZ API 
- [x] Python Versions 
  - >3.7
- [x] JKTerry and Mark as owners 
- [x] TOTP 
- [x] Google Analytics 
- [x] License 
- [x] Donations

**Comment by MatPoliquin** [comment]
@elliottower For "Support serialization via Pickle/EzPickle", you mean for serializing envs?

**Comment by MatPoliquin** [comment]
@elliottower For explicit versioning, does shimmy plan to use that? looking at the repo it's still using the 3 number versions

**Comment by elliottower** [comment]
Oh sorry I think there’s a misunderstanding. Explicit versioning is for environments so like whenever you change the logic or anything that would make training go differently, change it from pong_v0 to v1, etc. For emulated envs like here I would think it would be more similar to shimmy having DmControlCompatibilityWrapperV0 for example, which gets updated when it loads the envs differently or would somehow otherwise affect training like rewards changed etc. See the farama.org project standards for more info

**Comment by MatPoliquin** [comment]
@elliottower So the checklist is progressing, there is two remaining items:
Google Analytics ID, where can I get the ID that Farama uses?
For the Farama notifications, is there a guide on how to integrate that?

**Comment by elliottower** [comment]
Tagged you in a discord thread with the web dev guy manuel and a thread in all devs about farama notifications

**Comment by MatPoliquin** [comment]
I think we are complete. The only point we won't do for now is the Pickle serialization
